---
title: "Explore Variables"
output: html_document
---

```{r setup, include=FALSE}
```

```{r}
library(haven)

# Load custom functions.
source("function_library.R")

data = read_spss("inbound/MASTER Full Probationer Merged Jan 2012.sav")
dim(data)

# Too many columns to list them all.
# paste(names(data), collapse=", ")

head(names(data))
tail(names(data))


# Initialize to an empty list.
keep_fields = list()

###################
# Primary participant id.
keep_fields$STUDYID = "studyid"

# Review the site fields.
review_by_string(data, "Site", ignore_case=F)
keep_fields$PB_Site = "site"


###################
# COVARIATES.

# Review possible age fields.
review_by_string(data, "Age")

# Seems reasonable.
table(data$AgeComputed, useNA="ifany")
keep_fields$AgeComputed = "age"

# Average age by site.
# This matches table 1 in Manchak et al. 2014 "High fidelity..."
tapply(data$AgeComputed, data$PB_Site, FUN=function(group) mean(group, na.rm=T))

review_by_string(data, "Gender")
table(data$PB_Gender1.1, data$PB_Gender3, useNA="ifany")
keep_fields$PB_Gender1.1 = "gender"

review_by_string(data, "Race")
# Looks reasonable but need to determine the codes.
table(data$PB_race1.5)
keep_fields$PB_race1.5 = "race"

review_by_string(data, "probation")

table(data$YRORLESSPROBATION, useNA="ifany")

#keep_fields$YRORLESSPROBATION = "year_or_less_probation"

# Index offense or age at first offense?
# May need to calculate age based on this date.
review_by_string(data, "index")
review_by_string(data, "first")
# Still need to figure out index offense.

keep_fields$PB_numarrest = "number_of_arrests"
#keep_fields$PB_everarrested18.3 = "father_arrested"

# Recent violence.
review_by_string(data, "violence")

# Past psychiatric hospitalization.
review_by_string(data, "hospital")

# Colorado symptom index score.
keep_fields$PB_CSITotal = "CSI"

# Global assessment of function
keep_fields$PB_GAFscore21 = "GAF"

# Anxiety subscale of personal assessment inventory.
review_by_string(data, "anxiety")

# Most serious crime ever
keep_fields$PB_rcrimes2.2 = "most_serious_crime"

# Most serious charge from record
keep_fields$PB_rec4sericharge = "most_serious_charge"

# PAI subscale scores
keep_fields$PB_SOM = "PAI_somatization"
keep_fields$PB_ANX = "PAI_anxiety_physio"
keep_fields$PB_ARD = "PAI_anxiety_dis"
keep_fields$PB_DEP = "PAI_depression"
keep_fields$PB_MAN = "PAI_paranoia"
keep_fields$PB_SCZ = "PAI_schizophrenia"
keep_fields$PB_BOR = "PAI_borderline" 
keep_fields$PB_ANT = "PAI_antisocial"
keep_fields$PB_AGG = "PAI_aggression"
keep_fields$PB_PAIALC = "PAI_alcohol"
keep_fields$PB_PAIDRG = "PAI_drug"

# categorical variable for age at first arrest

keep_fields$PB_rehowold2.3 = "age_first_arrest_categ"

keep_fields$PB_howold2.3 = "age_first_arrest"

# recent violence prior to placement

keep_fields$PB_aggvio6mo="recent_violence"

# length on probation

keep_fields$LOProbation="length_probation"

# number of times hospitalized


#keep_fields$PB_times5.2a="times_hospitalized"

keep_fields$PB_barehand18.4a="beaten_barehand"

keep_fields$PB_somethinghrd18.5a="beaten_hard"

keep_fields$PB_whipstrap18.6a="beaten_whipstrap"

keep_fields$PB_bothersexlly18.11="bothered_sexually"

keep_fields$PB_txcompliance="tx_compliance"


covariates = clean_dataset(data, keep_fields)

# Additonal cleanup of covariate fields.

# Convert site from labelled to numeric.
covariates$site = as.numeric(covariates$site)
table(covariates$site, useNA="ifany")

# Race should be a factor.
covariates$race = as.factor(covariates$race)
table(covariates$race)

# Add days not at risk from risk file
riskdata = read_spss("inbound/All other CJ outcomes_Baseline Start_Jan 2012.sav")

covariates$totnightsnotatriskbto24 = riskdata$totnightsnotatriskbto24

save(covariates, file="data/covariates.RData")

############################################
############################################
# Violence data.
data = read_spss("inbound/FINAL Merged PO and Probationer FULL Violence File_Aug 2014.sav")
names(data)
dim(data)

outcome = review_by_string(data, "AnyFullCONSERV")[1]
outcome

keep_fields = list()
keep_fields[[outcome]] = "any_violence"

tab = table(data[, outcome], useNA="ifany")
tab
prop.table(tab)


assignment = "PB_Site"
tab = table(data[, assignment], useNA="ifany")
tab
prop.table(tab)
keep_fields[[assignment]] = "site"

keep_fields$STUDYID = "studyid"

violence = clean_dataset(data, keep_fields)

# Convert site from "labelled" to numeric so that it can be merged on.
violence$site = as.numeric(violence$site)
table(violence$site)

save(violence, file="data/violence.RData")


############################################
############################################
# Arrest data.
data = read_spss("inbound/FBI Arrests - File 3 - Baseline interview date - Jan 2012.sav")
names(data)
dim(data)

keep_fields = list()
keep_fields$StudyID = "studyid"
keep_fields$PB_site = "site"
keep_fields$anyarrest0to2yr = "any_arrest"
keep_fields$indexoffense = "index_offense"

arrest = clean_dataset(data, keep_fields)

# Review missing data in the arrest column.
table(arrest$any_arrest, useNA="ifany")
sum(arrest$any_arrest == 99)
# 99 is a code for NA in the original arrest dataset.
arrest$any_arrest[arrest$any_arrest == 99] = NA
table(arrest$any_arrest, useNA="ifany")

# Convert site from "labelled" to numeric so that it can be merged on.
arrest$site = as.numeric(arrest$site)

# index_offense should be a factor

arrest$index_offense[arrest$index_offense == 99] = NA


save(arrest, file="data/arrests.RData")

############################################
############################################
# Combined dataset.
library(dplyr)

# First combine outcomes.
data = left_join(violence, arrest, by=c("studyid", "site"))
dim(data)
names(data)
table(data$any_violence)
table(data$any_arrest)

# Then add on covariates.
data = left_join(data, covariates, by=c("studyid", "site"))
dim(data)
names(data)

# Site 0 is actually the treatment site (speciality probation).
data$treatment = as.numeric(data$site == 0)
table(data$treatment, data$site, useNA="ifany")
data$site = NULL

# Make studyid and treatment the first two variables in the dataset.
data = cbind(data[, c("studyid", "treatment")], subset(data, select=-c(studyid, treatment)))
names(data)

# Review NAs.
apply(data, MARGIN=2, FUN=function(col) { sum(is.na(col)) })

outcomes = c("any_violence", "any_arrest")

# Impute missing data
# WARNING: this is imputed misisng outcome data as well, which needs to be reverted.
data = impute_missing_values(data, skip_vars = outcomes)

# Check NAs.
apply(data, MARGIN=2, FUN=function(col) { sum(is.na(col)) })

save(data, file="data/analysis-dataset.RData")

```

