---
title: "TMLE"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("function_library.R")
load_all_libraries()
cluster = setup_parallelism()

# Increase to 15 CV folds for estimate_effect()
cv_folds = 15
crossvalidate=T

library(ggplot2)

# Customize ggplot2 default theme.
theme_set(theme_light() + theme(plot.background = element_rect(color = "grey", fill="#f5f5f5")))
```

## Data prep

```{r cache=F}
load("data/analysis-dataset.RData")

# Check for missing indicators that are all 0.
colMeans(W_arrest[, colnames(W_arrest)[42:ncol(W_arrest)]])
  
# Remove miss_index_offense and miss_recent_violence because sd = 0.
#W_arrest = subset(W_arrest, select=-c(miss_index_offense, miss_recent_violence))
dim(W_arrest)

# Naive estimate
summary(glm(any_arrest ~ treatment, data=data_arrest, family="gaussian"))
summary(glm(any_violence ~ treatment, data=data_violence, family="gaussian"))

(table("Tx"=data_arrest$treatment, "Arrest"=data_arrest$any_arrest, useNA="ifany"))
```

```{r}
# Set dsa=T to re-enable DSA, but it will slow down the modeling significantly.
custom_lib = create_SL_lib(num_cols = ncol(W_arrest), detailed_names = T, xgb="small")
#custom_lib = create_SL_lib(num_cols = ncol(W_arrest), detailed_names = T, xgb=F, rf=F, glmnet_size=5)
sl_lib = custom_lib$lib
sl_lib
```

## TMLE

### Arrest analysis

```{r cache=T, eval=T}

time = system.time({
  # Hide long output from stepAIC.
  out = capture.output({
    # Takes about 5-10 minutes.
    result_arrest = tmle(Y=data_arrest$any_arrest, A=data_arrest$treatment,
                  W=W_arrest, family="binomial",
                  Q.SL.library = sl_lib, g.SL.library = sl_lib)
  })
})
time
result_arrest$time = time

# Very significant reduction in arrest rate.
result_arrest

save(result_arrest, file="data/tmle-arrest.RData")
```

```{r cache=T}
# Compare to manual TMLE.

set.seed(1)

time = system.time({
  # Takes about 2-10 minutes without outer cross-validation.
  # 10x that with outer cross-validation over 10 folds.
  result_arrest2 = estimate_effect(Y=data_arrest$any_arrest,
                      A=data_arrest$treatment, W=W_arrest,
                      parallel = "multicore", sl_lib = sl_lib,
                      cluster=cluster, cv_folds = cv_folds,
                      crossvalidate=crossvalidate, outer_cv_folds = 10)
})
time
result_arrest2$time = time
result_arrest2

save(result_arrest2, file="data/tmle-arrest2.RData")
```

```{r cache=T}
# We put this in a separate block so that we can modify without invalidating the analysis cache.

# Review SL weights.
result_arrest2$qinit
result_arrest2$ghat
names(result_arrest2)

cat("Review distribution of Ghat.\n")
summary(result_arrest2$ghat$SL.predict)

cat("Review distribution of weights (1/Ghat).\n")

# Examine 1/gHatAW and 1/(1-gHatAW).
wgts = pmax(1/result_arrest2$gHatAW, 1/(1-result_arrest2$gHatAW))
summary(wgts)
# Review 10 highest weights.
wgts[order(wgts, decreasing=T)][1:10]

qplot(wgts) + ggtitle("Arrest g-weights (1/ghat)")
ggsave(filename="visuals/gwgts-arrest.png")

qplot(result_arrest2$ghat$SL.predict) + geom_density() + xlab("gHat1W distribution")
ggsave(filename="visuals/ghat-arrest.png")

if (is.element("qinit_cv", names(result_arrest2))) {
	# Review outer cross-validation results.
  sum = summary(result_arrest2$qinit_cv)
  # Reorder by ascending risk.
  sum = sum$Table[order(sum$Table$Ave, decreasing=F), ]
  print(sum)
  rownames(sum) = NULL
  if (T) {
    print(xtable(sum[1:10, c("Algorithm", "Ave", "se")], digits=3, caption="Arrest - qinit - risk estimates"))
  }

	sum = summary(result_arrest2$ghat_cv)
	# Reorder by ascending risk.
  sum = sum$Table[order(sum$Table$Ave, decreasing=F), ]
  print(sum)
  rownames(sum) = NULL
  if (T) {
    xtable(sum[1:10, c("Algorithm", "Ave", "se")], digits=3, caption = "Arrest - gHat - risk estimates")
  }

}
```

```{r cache=T, results="asis"}
# Output the weight tables in a separate block so that we can set results=asis.

if (is.element("qinit_cv", names(result_arrest2))) {
	# Review outer cross-validation results.
  
  # Qinit SL meta-weights
	wgts = cvSL_review_weights(result_arrest2$qinit_cv)
	# Limit to models with a SD > 0.
	wgts = wgts[wgts[, 2] > 0, ]
	# Re-order by descending mean weight.
	wgts = wgts[order(wgts[, 1], decreasing=T), ]
  cat("\nQinit weights:\n")
  colnames(wgts) = c("Mean(wgt)", "S.D.", "Min", "Max")
	print(xtable(wgts), type = "html")

	if (T) {	
	  # For presentation/paper
	  print(xtable(wgts[1:10, ],caption="Arrest - qInit - meta-weights"), type="latex")
	}

  # ghat SL meta-weights
	wgts = cvSL_review_weights(result_arrest2$ghat_cv)
	# Limit to models with a SD > 0.
	wgts = wgts[wgts[, 2] > 0, ]
	# Re-order by descending mean weight.
	wgts = wgts[order(wgts[, 1], decreasing=T), ]
	 
  cat("\n<br /><br />gHat weights:\n")
    colnames(wgts) = c("Mean(wgt)", "S.D.", "Min", "Max")
	print(xtable(wgts), type = "html")
	if (T) {
	  # For presentation/paper
	  print(xtable(wgts[1:10, ], caption="Arrest - gHat - meta-weights"), type="latex")
	}
}
```

### Violence analysis

```{r cache=T, eval=T}

set.seed(1)

time = system.time({
  # Hide long output from stepAIC.
  out = capture.output({
    # Takes about 5-10 minutes on CK's laptop.
    result_violence = tmle(Y=data_violence$any_violence, A=data_violence$treatment, W=W_violence, family="binomial", Q.SL.library = sl_lib, g.SL.library = sl_lib)
  })
})
time
result_violence$time = time

# No effect on violence.
result_violence

save(result_violence, file="data/tmle-violence.RData")

```

```{r cache=T}

set.seed(1)
# Compare to our own code:

time = system.time({
  # Takes about 2-10 minutes without outer cross-validation.
  # 10x that with outer cross-validation over 10 folds.
  result_violence2 = estimate_effect(Y=data_violence$any_violence, 
                          A=data_violence$treatment, W=W_violence,
                          parallel = "multicore", sl_lib = sl_lib,
                          cv_folds = cv_folds, cluster=cluster,
      	  	  						crossvalidate=crossvalidate, outer_cv_folds = 10)
})
time
result_violence2$time = time
result_violence2

save(result_violence2, file="data/tmle-violence2.RData")
```

```{r cache=T}
# We put this in a separate block so that we can modify without invalidating the analysis cache.

# Review SL weights.
result_violence2$qinit
result_violence2$ghat

cat("Review distribution of Ghat.\n")
summary(result_violence2$ghat$SL.predict)

cat("Review distribution of weights (1/Ghat).\n")
# Examine 1/gHatAW and 1/(1-gHatAW).
wgts = pmax(1/result_arrest2$gHatAW, 1/(1-result_arrest2$gHatAW))
summary(wgts)
# Review 10 highest weights.
wgts[order(wgts, decreasing=T)][1:10]
qplot(wgts) + ggtitle("Violence g-weights (1/ghat)")
ggsave(filename="visuals/gwgts-violence.png")

qplot(result_violence2$ghat$SL.predict) + geom_density() + xlab("gHat1W distribution")
ggsave(filename="visuals/ghat-violence.png")

if (is.element("qinit_cv", names(result_violence2))) {
	# Review outer cross-validation results.
  sum = summary(result_violence2$qinit_cv)
  # Reorder by ascending risk.
  sum = sum$Table[order(sum$Table$Ave, decreasing=F), ]
  print(sum)
  rownames(sum) = NULL
  if (T) {
    xtable(sum[1:10, c("Algorithm", "Ave", "se")], digits=3, caption="Violence - risk estimates - qInit")
  }

	sum = summary(result_violence2$ghat_cv)
	# Reorder by ascending risk.
  sum = sum$Table[order(sum$Table$Ave, decreasing=F), ]
  print(sum)
  rownames(sum) = NULL
  if (T) {
    xtable(sum[1:10, c("Algorithm", "Ave", "se")], digits=3, caption = "Violence - risk estimates - gHat")
  }
}

```

```{r cache=T, results="asis"}
# Output the weight tables in a separate block so that we can set results=asis.

if (is.element("qinit_cv", names(result_violence2))) {
	# Review outer cross-validation results.
  
  # Qinit SL meta-weights.
	wgts = cvSL_review_weights(result_violence2$qinit_cv)
	# Limit to models with a SD > 0.
	wgts = wgts[wgts[, 2] > 0, ]
	# Re-order by descending mean weight.
	wgts = wgts[order(wgts[, 1], decreasing=T), ]
  cat("Qinit weights:\n")
  colnames(wgts) = c("Mean(wgt)", "S.D.", "Min", "Max")
	print(xtable(wgts), type = "html")
	if (T) {
	  # For presentation/paper
	  print(xtable(wgts[1:10, ], caption="Violence - qInit - meta-weights"), type="latex")
	}
	
  # gHat SL meta-weights.
	wgts = cvSL_review_weights(result_violence2$ghat_cv)
	# Limit to models with a SD > 0.
	wgts = wgts[wgts[, 2] > 0, ]
	# Re-order by descending mean weight.
	wgts = wgts[order(wgts[, 1], decreasing=T), ]
	
  cat("\n<br /><br />gHat weights:\n")
  colnames(wgts) = c("Mean(wgt)", "S.D.", "Min", "Max")
	print(xtable(wgts), type = "html")
	if (T) {
	  # For presentation/paper
	  print(xtable(wgts[1:10, ], caption="Violence - gHat - meta-weights"), type="latex")
	}
}
```

